version: '2'
services:
  mongodb:
    image: "mongo"
    ports:
     - "27017:27017"
  backend:
    build: ./node-backend/
    ports:
      - "3001:3001"
    volumes:
      - ./node-backend:/usr/src/app
    depends_on:
      - mongodb
  frontend:
    build: ./react-frontend/
    ports:
      - "3000:3000"
    volumes:
      - ./react-frontend:/usr/src/app
    depends_on:
      - backend
